### ISSUE TITLE
Interactive UI design

### ISSUE THREAD

**Issue by ShafiMohammad09** [SchBenedikt/schbenedikt.github.io#32]
hello there 👋,
i have viewed the web page , its functioning is quite good and impressive. but the UI design of the web page is not much blending with the page.
so, as a UI designer and a Front-end Developer i would love to work on the user interface of the page.

**Comment by SchBenedikt** [comment]
Thanks for your feedback - of course you can work on it. What changes do you envision?

**Comment by ShafiMohammad09** [comment]
I've noticed that most of the main content is clustered in one area. I can either rework the UI layout or make subtle adjustments. Considering the current layout, I believe applying a glassmorphism effect would greatly enhance the page. You can check out similar effects on google like [here 🔗](https://www.google.com/search?q=glassmorphism+figma&sca_esv=569682931&rlz=1C1ONGR_enIN1068IN1068&tbm=isch&sxsrf=AM9HkKntgkn4qOIPrcmlqmwutq8e0EwbpA:1696070107660&source=lnms&sa=X&ved=2ahUKEwjbuZ_CkdKBAxW1TGwGHawUAOsQ_AUoAnoECAIQBA&biw=767&bih=694&dpr=1.25#imgrc=3dWqR8BHHAyq2M)

**Comment by SchBenedikt** [comment]
Yes - a Glassmorphism design for this website would definitely look great too!
