### ISSUE TITLE
Github username input prediction

### ISSUE THREAD

**Issue by SchBenedikt** [SchBenedikt/schbenedikt.github.io#5]
We'll try to add a code next to "predict" the username when entering the Github username. It is best to simply get the username from a username.txt file.

**Comment by LaansDole** [comment]
Cool features, I can take a look into this with you @SchBenedikt

**Comment by LaansDole** [comment]
@SchBenedikt I have done the functionality of this feature, I have not done the styling yet but you can take a look

**Comment by SchBenedikt** [comment]
Thanks, I'll check it out later!

**Comment by LaansDole** [comment]
> Thank you for doing everything - but I'm short on time right now, so I may have to take a closer look at this later! It should replace the Github Username input form. During the username search you should also be able to select the suggested usernames. How do you find that?

You can take a look on the preview, basically I just went through github api. The rest is handling with javascript
