### ISSUE TITLE
Slow Overlay

### ISSUE THREAD

**Issue by LaansDole** [SchBenedikt/schbenedikt.github.io#7]
The styling looks great, but for some reasons the overlay is very slow and glitchy, it would be better if it is another page

**Comment by SchBenedikt** [comment]
So that you can tap on each project and then a new page is simply there for each description?

**Comment by LaansDole** [comment]
Yes, it's like an overlay page except it's not an overlay

**Comment by SchBenedikt** [comment]
Yes, if you like to do that!

**Comment by SchBenedikt** [comment]
Will be done with #10
Feature changed.
